const products = [
 {id:'cpu-amd',cat:'CPU',brand:'AMD',name:'Ryzen 7 9800X3D',price:479,score:96,emoji:'▣',specs:{'Núcleos / hilos':'8 / 16','Frecuencia boost':'5.2 GHz','Caché':'104 MB','TDP':'120 W','Socket':'AM5'}},
 {id:'cpu-intel',cat:'CPU',brand:'Intel',name:'Core Ultra 7 265K',price:399,score:88,emoji:'▣',specs:{'Núcleos / hilos':'20 / 20','Frecuencia boost':'5.5 GHz','Caché':'66 MB','TDP':'125 W','Socket':'LGA1851'}},
 {id:'gpu-nvidia',cat:'GPU',brand:'NVIDIA',name:'GeForce RTX 5070 Ti',price:749,score:94,emoji:'▤',specs:{'VRAM':'16 GB GDDR7','Boost':'2.45 GHz','Bus de memoria':'256-bit','Consumo':'300 W','Ray tracing':'4ª generación'}},
 {id:'gpu-amd',cat:'GPU',brand:'AMD',name:'Radeon RX 9070 XT',price:599,score:92,emoji:'▤',specs:{'VRAM':'16 GB GDDR6','Boost':'2.97 GHz','Bus de memoria':'256-bit','Consumo':'304 W','Ray tracing':'3ª generación'}},
 {id:'ram-corsair',cat:'RAM',brand:'Corsair',name:'Vengeance RGB 32 GB',price:119,score:91,emoji:'▥',specs:{'Capacidad':'32 GB (2×16)','Velocidad':'6000 MT/s','Latencia':'CL30','Tipo':'DDR5','Voltaje':'1.40 V'}},
 {id:'ram-gskill',cat:'RAM',brand:'G.Skill',name:'Trident Z5 Neo 32 GB',price:124,score:93,emoji:'▥',specs:{'Capacidad':'32 GB (2×16)','Velocidad':'6000 MT/s','Latencia':'CL30','Tipo':'DDR5','Voltaje':'1.35 V'}},
 {id:'mb-asus',cat:'Placa base',brand:'ASUS',name:'ROG Strix X870E-E',price:499,score:94,emoji:'▦',specs:{'Socket':'AM5','Formato':'ATX','Memoria':'DDR5 · 192 GB','Wi-Fi':'Wi-Fi 7','M.2':'5 ranuras'}},
 {id:'mb-msi',cat:'Placa base',brand:'MSI',name:'MAG X870 Tomahawk',price:299,score:91,emoji:'▦',specs:{'Socket':'AM5','Formato':'ATX','Memoria':'DDR5 · 256 GB','Wi-Fi':'Wi-Fi 7','M.2':'4 ranuras'}},
 {id:'ssd-samsung',cat:'Almacenamiento',brand:'Samsung',name:'990 Pro 2 TB',price:169,score:95,emoji:'▰',specs:{'Capacidad':'2 TB','Lectura':'7450 MB/s','Escritura':'6900 MB/s','Interfaz':'PCIe 4.0','Garantía':'5 años'}},
 {id:'ssd-wd',cat:'Almacenamiento',brand:'WD',name:'Black SN850X 2 TB',price:149,score:93,emoji:'▰',specs:{'Capacidad':'2 TB','Lectura':'7300 MB/s','Escritura':'6600 MB/s','Interfaz':'PCIe 4.0','Garantía':'5 años'}},
 {id:'psu-seasonic',cat:'Fuente',brand:'Seasonic',name:'Vertex GX-850',price:189,score:94,emoji:'◉',specs:{'Potencia':'850 W','Certificación':'80+ Gold','Estándar':'ATX 3.0','Modular':'Sí','Garantía':'12 años'}},
 {id:'psu-corsair',cat:'Fuente',brand:'Corsair',name:'RM850x Shift',price:159,score:92,emoji:'◉',specs:{'Potencia':'850 W','Certificación':'80+ Gold','Estándar':'ATX 3.0','Modular':'Sí','Garantía':'10 años'}},
 {id:'cool-nzxt',cat:'Refrigeración',brand:'NZXT',name:'Kraken Elite 360',price:279,score:91,emoji:'❄',specs:{'Tipo':'AIO líquido','Radiador':'360 mm','Ruido':'33.9 dBA','Pantalla':'LCD 2.72”','Garantía':'6 años'}},
 {id:'cool-arctic',cat:'Refrigeración',brand:'Arctic',name:'Liquid Freezer III 360',price:129,score:95,emoji:'❄',specs:{'Tipo':'AIO líquido','Radiador':'360 mm','Ruido':'23.5 dBA','Pantalla':'No','Garantía':'6 años'}},
 {id:'case-fractal',cat:'Gabinete',brand:'Fractal',name:'North XL',price:179,score:94,emoji:'▯',specs:{'Formato':'Full tower','Placa máxima':'E-ATX','GPU máxima':'413 mm','Ventiladores':'3 incluidos','Peso':'9.7 kg'}},
 {id:'case-lianli',cat:'Gabinete',brand:'Lian Li',name:'O11 Dynamic EVO',price:169,score:93,emoji:'▯',specs:{'Formato':'Mid tower','Placa máxima':'E-ATX','GPU máxima':'426 mm','Ventiladores':'0 incluidos','Peso':'12.7 kg'}},
 {id:'mon-lg',cat:'Monitor',brand:'LG',name:'UltraGear 27GS95QE',price:699,score:94,emoji:'▱',specs:{'Panel':'OLED','Resolución':'2560 × 1440','Frecuencia':'240 Hz','Respuesta':'0.03 ms','HDR':'HDR10'}},
 {id:'mon-samsung',cat:'Monitor',brand:'Samsung',name:'Odyssey OLED G6',price:749,score:95,emoji:'▱',specs:{'Panel':'QD-OLED','Resolución':'2560 × 1440','Frecuencia':'360 Hz','Respuesta':'0.03 ms','HDR':'HDR10+ Gaming'}},
 {id:'kb-razer',cat:'Teclado',brand:'Razer',name:'Huntsman V3 Pro TKL',price:219,score:92,emoji:'⌨',specs:{'Formato':'TKL','Switch':'Óptico analógico','Conexión':'Cable','Iluminación':'RGB','Peso':'719 g'}},
 {id:'kb-logi',cat:'Teclado',brand:'Logitech',name:'G Pro X TKL Rapid',price:169,score:91,emoji:'⌨',specs:{'Formato':'TKL','Switch':'Magnético','Conexión':'Inalámbrica','Iluminación':'RGB','Peso':'1035 g'}},
 {id:'mouse-logi',cat:'Mouse',brand:'Logitech',name:'G Pro X Superlight 2',price:159,score:95,emoji:'◒',specs:{'Sensor':'HERO 2','DPI':'44000','Peso':'60 g','Conexión':'Inalámbrica','Batería':'95 horas'}},
 {id:'mouse-razer',cat:'Mouse',brand:'Razer',name:'Viper V3 Pro',price:159,score:96,emoji:'◒',specs:{'Sensor':'Focus Pro 35K','DPI':'35000','Peso':'54 g','Conexión':'Inalámbrica','Batería':'95 horas'}},
 {id:'print-hp',cat:'Impresora',brand:'HP',name:'OfficeJet Pro 9125e',price:209,score:88,emoji:'▣',specs:{'Tecnología':'Inyección térmica','Color':'Sí','Velocidad':'22 ppm','Dúplex':'Automático','Conexión':'Wi-Fi · USB'}},
 {id:'print-epson',cat:'Impresora',brand:'Epson',name:'EcoTank ET-4850',price:399,score:93,emoji:'▣',specs:{'Tecnología':'Tanque de tinta','Color':'Sí','Velocidad':'15.5 ppm','Dúplex':'Automático','Conexión':'Wi-Fi · Ethernet'}},
 {id:'speaker-edifier',cat:'Bocinas',brand:'Edifier',name:'R1280DBs',price:159,score:92,emoji:'◖',specs:{'Potencia':'42 W RMS','Canales':'2.0','Respuesta':'51 Hz–20 kHz','Bluetooth':'5.0','Subwoofer':'Salida disponible'}},
 {id:'speaker-logi',cat:'Bocinas',brand:'Logitech',name:'Z407',price:119,score:87,emoji:'◖',specs:{'Potencia':'40 W RMS','Canales':'2.1','Respuesta':'40 Hz–20 kHz','Bluetooth':'5.0','Subwoofer':'Incluido'}},
 {id:'head-sony',cat:'Audífonos',brand:'Sony',name:'INZONE H9',price:299,score:91,emoji:'Ω',specs:{'Tipo':'Over-ear','Conexión':'2.4 GHz · Bluetooth','Cancelación':'Activa','Batería':'32 horas','Peso':'330 g'}},
 {id:'head-hyperx',cat:'Audífonos',brand:'HyperX',name:'Cloud III Wireless',price:169,score:93,emoji:'Ω',specs:{'Tipo':'Over-ear','Conexión':'2.4 GHz','Cancelación':'Pasiva','Batería':'120 horas','Peso':'342 g'}},
 {id:'web-logi',cat:'Webcam',brand:'Logitech',name:'MX Brio',price:199,score:94,emoji:'◉',specs:{'Resolución':'4K','Fotogramas':'30 fps 4K','Enfoque':'Automático','Micrófono':'Doble','Campo de visión':'90°'}},
 {id:'web-elgato',cat:'Webcam',brand:'Elgato',name:'Facecam MK.2',price:149,score:92,emoji:'◉',specs:{'Resolución':'1080p','Fotogramas':'60 fps','Enfoque':'Fijo','Micrófono':'No','Campo de visión':'84°'}},
 {id:'mic-blue',cat:'Micrófono',brand:'Blue',name:'Yeti X',price:169,score:91,emoji:'♩',specs:{'Patrones':'4','Frecuencia':'20 Hz–20 kHz','Resolución':'24-bit / 48 kHz','Conexión':'USB','Monitoreo':'3.5 mm'}},
 {id:'mic-hyperx',cat:'Micrófono',brand:'HyperX',name:'QuadCast 2',price:149,score:92,emoji:'♩',specs:{'Patrones':'4','Frecuencia':'20 Hz–20 kHz','Resolución':'24-bit / 96 kHz','Conexión':'USB-C','Monitoreo':'3.5 mm'}},
 {id:'ups-apc',cat:'UPS',brand:'APC',name:'Back-UPS Pro 1500VA',price:249,score:94,emoji:'ϟ',specs:{'Capacidad':'1500 VA','Potencia':'900 W','Topología':'Line-interactive','Salidas':'10','Pantalla':'LCD'}},
 {id:'ups-cyber',cat:'UPS',brand:'CyberPower',name:'CP1500PFCLCD',price:219,score:95,emoji:'ϟ',specs:{'Capacidad':'1500 VA','Potencia':'1000 W','Topología':'Line-interactive','Salidas':'12','Pantalla':'LCD'}},
 {id:'cap-elgato',cat:'Capturadora',brand:'Elgato',name:'4K X',price:229,score:94,emoji:'▣',specs:{'Captura máxima':'4K 144 Hz','Interfaz':'USB 3.2','HDR':'Sí','VRR':'Sí','Passthrough':'4K 144 Hz'}},
 {id:'cap-aver',cat:'Capturadora',brand:'AVerMedia',name:'Live Gamer Ultra 2.1',price:249,score:93,emoji:'▣',specs:{'Captura máxima':'4K 60 Hz','Interfaz':'USB 3.2','HDR':'Sí','VRR':'Sí','Passthrough':'4K 144 Hz'}},
 {id:'net-asus',cat:'Red',brand:'ASUS',name:'PCE-BE92BT',price:99,score:94,emoji:'⌁',specs:{'Wi-Fi':'Wi-Fi 7','Velocidad':'5.8 Gbps','Bluetooth':'5.4','Bandas':'Tri-band','Interfaz':'PCIe'}},
 {id:'net-tp',cat:'Red',brand:'TP-Link',name:'Archer TBE550E',price:89,score:93,emoji:'⌁',specs:{'Wi-Fi':'Wi-Fi 7','Velocidad':'5.8 Gbps','Bluetooth':'5.4','Bandas':'Tri-band','Interfaz':'PCIe'}}
];

const cats=['Todos',...new Set(products.map(p=>p.cat))];
let activeCat='Todos', sideToPick='a', selected={a:null,b:null};
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)};

function renderCats(){ $('#categories').innerHTML=cats.map(c=>`<button class="${c===activeCat?'active':''}" data-cat="${c}">${c}</button>`).join(''); }
function filtered(){const q=$('#catalogSearch').value.trim().toLowerCase();let list=products.filter(p=>(activeCat==='Todos'||p.cat===activeCat)&&(`${p.name} ${p.brand} ${Object.values(p.specs).join(' ')}`).toLowerCase().includes(q));const sort=$('#sortSelect').value;if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort==='priceDesc')list.sort((a,b)=>b.price-a.price);if(sort==='score')list.sort((a,b)=>b.score-a.score);return list}
function renderProducts(){const list=filtered();$('#resultsCount').textContent=`${list.length} resultados`;$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-top"><span class="tag">${p.cat.toUpperCase()}</span><span class="rating">★ ${p.score/10}</span></div><div class="product-visual">${p.emoji}</div><h3>${p.name}</h3><p>${p.brand} · ${Object.values(p.specs).slice(0,2).join(' · ')}</p><div class="price-row"><b>${money(p.price)}</b><button data-add="${p.id}" title="Comparar">＋</button></div></article>`).join('')||'<p>No encontramos componentes con esos filtros.</p>';}
function pickerItems(q=''){let list=products;if(selected.a||selected.b){const other=selected[sideToPick==='a'?'b':'a'];if(other)list=list.filter(p=>p.cat===other.cat)}q=q.toLowerCase();list=list.filter(p=>(p.name+' '+p.brand).toLowerCase().includes(q));$('#pickerList').innerHTML=list.map(p=>`<button class="picker-item" data-pick="${p.id}"><span class="emoji">${p.emoji}</span><span><strong>${p.name}</strong><small>${p.brand} · ${p.cat}</small></span><b>${money(p.price)}</b></button>`).join('')||'<p>Sin resultados.</p>'}
function openPicker(side){sideToPick=side;const other=selected[side==='a'?'b':'a'];$('#pickerTitle').textContent=other?`Elige otro ${other.cat}`:'Elige un componente';$('#pickerSearch').value='';pickerItems();$('#pickerModal').showModal()}
function pick(id){const p=products.find(x=>x.id===id),other=selected[sideToPick==='a'?'b':'a'];if(other&&other.cat!==p.cat)return toast('Elige un componente de la misma categoría');selected[sideToPick]=p;$('#pickerModal').close();renderSelection();if(other&&other.brand===p.brand)toast('Consejo: compara fabricantes distintos para una decisión más útil')}
function renderSelection(){['a','b'].forEach(side=>{const p=selected[side],el=$(`#pick${side.toUpperCase()}`);if(!p){el.className='pick-card';el.innerHTML=`<span class="side-label">COMPONENTE ${side.toUpperCase()}</span><span class="plus">＋</span><strong>Seleccionar componente</strong><small>${side==='a'?'Haz clic para explorar el catálogo':'Elige otra marca para comparar'}</small>`;return}el.className='pick-card selected';el.innerHTML=`<span class="side-label">COMPONENTE ${side.toUpperCase()}</span><span class="product-emoji">${p.emoji}</span><strong>${p.name}</strong><small>${p.brand} · ${p.cat}</small><span class="picked-meta"><b>${money(p.price)}</b><small>CAMBIAR ↗</small></span>`});renderComparison()}
function compareValue(a,b,key){const nums=[a,b].map(v=>parseFloat(String(v).replace(/[^0-9.]/g,'')));if(nums.some(Number.isNaN)||nums[0]===nums[1])return['',''];const lowerWins=/consumo|tdp|ruido|peso|precio|latencia|respuesta/i.test(key);const aw=lowerWins?nums[0]<nums[1]:nums[0]>nums[1];return aw?['winner','']:['','winner']}
function renderComparison(){const box=$('#comparison'),a=selected.a,b=selected.b;if(!a||!b){box.classList.add('hidden');return}box.classList.remove('hidden');const winner=a.score===b.score?null:(a.score>b.score?a:b);const keys=[...new Set([...Object.keys(a.specs),...Object.keys(b.specs)])];box.innerHTML=`<div class="verdict"><div><small>VEREDICTO</small><h3>${winner?`${winner.name} obtiene la ventaja`:'Empate técnico'}</h3></div><div class="score"><span>PUNTUACIÓN</span><b>${a.score} — ${b.score}</b></div></div><div class="spec-row"><span class="${a.price<b.price?'winner':''}">${money(a.price)}</span><span>Precio estimado</span><span class="${b.price<a.price?'winner':''}">${money(b.price)}</span></div>${keys.map(k=>{const cls=compareValue(a.specs[k]||'—',b.specs[k]||'—',k);return`<div class="spec-row"><span class="${cls[0]}">${a.specs[k]||'—'}</span><span>${k}</span><span class="${cls[1]}">${b.specs[k]||'—'}</span></div>`}).join('')}`}
function apiState(){const key=localStorage.getItem('versus_channel3_key');$('#apiKey').value=key||'';$('#apiLabel').textContent=key?'API conectada':'Modo catálogo';document.querySelector('.status-dot').classList.toggle('online',!!key)}
async function remoteSearch(query){
 const key=localStorage.getItem('versus_channel3_key'); if(!key||!query.trim())return;
 toast('Consultando el catálogo global…');
 try{
  const res=await fetch('https://api.trychannel3.com/v1/search',{method:'POST',headers:{'x-api-key':key,'content-type':'application/json'},body:JSON.stringify({query:`${query} computer component`,filters:{category_ids:['hm8']},limit:20})});
  if(!res.ok)throw new Error(`API ${res.status}`); const data=await res.json(); const rows=data.products||data.results||data.items||[];
  rows.forEach((x,i)=>{const name=x.title||x.name||'Componente sin nombre';const brand=x.brand||x.manufacturer||name.split(' ')[0];const price=Number(x.price?.amount||x.price||x.min_price||0);const id=`api-${x.id||btoa(unescape(encodeURIComponent(name))).slice(0,12)}-${i}`;if(!products.some(p=>p.id===id))products.unshift({id,cat:activeCat==='Todos'?'Otros':activeCat,brand,name,price,score:80,emoji:'◇',specs:{'Disponibilidad':x.availability||x.in_stock?'Disponible':'Consultar','Fuente':'Channel3','Comercio':x.merchant_name||x.merchant||'Marketplace','Actualización':'En tiempo real'}})});
  renderProducts();$('#productCount').textContent=products.length;toast(`${rows.length} resultados recibidos de Channel3`);
 }catch(err){toast('No se pudo consultar la API. Mostrando el catálogo local.');console.warn('Channel3:',err)}
}

document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){activeCat=cat.dataset.cat;renderCats();renderProducts()}const add=e.target.closest('[data-add]');if(add){sideToPick=selected.a&&!selected.b?'b':'a';pick(add.dataset.add);document.querySelector('#comparador').scrollIntoView()}const p=e.target.closest('[data-pick]');if(p)pick(p.dataset.pick);const close=e.target.closest('[data-close]');if(close)document.getElementById(close.dataset.close).close()});
$('#pickA').onclick=()=>openPicker('a');$('#pickB').onclick=()=>openPicker('b');$('#pickerSearch').oninput=e=>pickerItems(e.target.value);$('#catalogSearch').oninput=renderProducts;$('#sortSelect').onchange=renderProducts;
$('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value;$('#catalogSearch').value=q;$('#catalogo').scrollIntoView();renderProducts();remoteSearch(q)}});$('#catalogSearch').addEventListener('keydown',e=>{if(e.key==='Enter')remoteSearch(e.target.value)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#heroSearch').focus()}});
$('#swapButton').onclick=()=>{[selected.a,selected.b]=[selected.b,selected.a];renderSelection()};$('#openApi').onclick=()=>{$('#apiModal').showModal()};
$('#saveApi').onclick=()=>{const key=$('#apiKey').value.trim();if(!key)return toast('Introduce una API key válida');localStorage.setItem('versus_channel3_key',key);apiState();$('#apiModal').close();toast('API configurada. Las búsquedas remotas están disponibles.')};
$('#removeApi').onclick=()=>{localStorage.removeItem('versus_channel3_key');apiState();$('#apiModal').close();toast('Catálogo local activado')};

$('#productCount').textContent=new Intl.NumberFormat('es').format(products.length);$('#categoryCount').textContent=cats.length-1;renderCats();renderProducts();renderSelection();apiState();
